name: Scrape

on:
  workflow_dispatch:
  schedule:
    # JST毎日0時に実行（UTC基準で15:00）
    - cron: "0 15 * * *"
    # もしUTCの毎日0時にしたいなら ↓ を使う
    # - cron: "0 0 * * *"

jobs:
  perform-fetch:
    runs-on: ubuntu-22.04
    permissions:
      contents: write   # リポジトリへコミットするために必要

    steps:
      - uses: actions/checkout@v4

      - uses: bedrock-apis/bds-download@v1
        with:
          out_dir: bedrock_server
          version: latest       # ← 'lastest' のtypo修正
          use_preview: false

      - name: Show files
        run: ls -la ./bedrock_server/

      - name: Commit downloaded files
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: "bedrock_server -f"   # bedrock_server配下を追加（-fで強制追跡）
          message: "Updated BDS (linux) files"
