name: Scrape
on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * *"   # JST 0:00（UTC+9）

jobs:
  perform-fetch:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: bedrock-apis/bds-download@v1
        with:
          out_dir: bedrock_server
          version: latest
          use_preview: false

      - name: Check GitHub 100MB limit
        id: sizecheck
        shell: bash
        run: |
          set -e
          # 100MB超のファイルがあるかチェック（1件でもあればtrue）
          if find bedrock_server -type f -size +100M -print -quit | grep -q .; then
            echo ">=100MB files found. Skip commit."
            # 参考出力（どれが大きいか知りたい場合）
            find bedrock_server -type f -size +100M -ls || true
            echo "skip_commit=true" >> "$GITHUB_OUTPUT"
          else
            echo "skip_commit=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit downloaded files
        if: steps.sizecheck.outputs.skip_commit == 'false'
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: "bedrock_server -f"
          message: "Update BDS (linux)"

      - name: Skip commit because of large files
        if: steps.sizecheck.outputs.skip_commit == 'true'
        run: echo "Commit skipped: at least one file is >= 100MB."
