name: Scrape
on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"   # 10分ごと（UTC）

concurrency:
  group: scrape
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y jq unzip

      - name: Git identity
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Make scripts executable
        run: chmod +x scripts/update_channel.sh scripts/update_main.sh

      - name: Update stable (worktree)
        env:
          GITHUB_TOKEN: ${{ github.token }}
          STRICT_SERIES: "true"   # 同系列(1.21.100.*など)優先で近似タグ
        run: bash -x scripts/update_channel.sh stable

      - name: Update preview (worktree)
        env:
          GITHUB_TOKEN: ${{ github.token }}
          STRICT_SERIES: "true"
        run: bash -x scripts/update_channel.sh preview

      - name: Update main (combine stable + preview)
        run: bash -x scripts/update_main.sh
