name: Scrape
on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * *"   # JST 0:00 (ActionsはUTC)

concurrency:
  group: scrape
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y jq unzip

      - name: Make scripts executable
        run: chmod +x update_channel.sh update_main.sh

      # 省リソースのため順番に（並列だとAPI/ネットワーク負荷↑）
      - name: Update stable
        env:
          GITHUB_TOKEN: ${{ github.token }}
          STRICT_SERIES: "true"
        run: update_channel.sh stable

      - name: Update preview
        env:
          GITHUB_TOKEN: ${{ github.token }}
          STRICT_SERIES: "true"
        run: update_channel.sh preview

      - name: Update main (combine stable + preview)
        run: update_main.sh
